package sid.learn.http.logingest;

import java.util.ArrayList;
import java.util.List;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import org.eclipse.microprofile.config.inject.ConfigProperties;


//@Path("/internal/logs")
@Path("/rest/customers/server/5b8188db-c6b9-44d5-9d08-f8dffa694218/features")
public class MockLogIngester {

    //private List<LogMsg> logMsgList = new ArrayList<>();


    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public Response sendLog(String msg) throws LogIngestException {

        List<LogMsg> logMsgList = new ArrayList<>();
        logMsgList.add(new LogMsg(msg));
        System.out.println("Log MSG received with size in bytes : " + msg.length());
//        return Response.status(207).entity("{\n"
//            + "    \"success\": false,\n"
//            + "    \"message\": \"Some events were not accepted. See the 'errors' property for additional information.\",\n"
//            + "    \"errors\": [\n"
//            + "        {\n"
//            + "            \"code\": 402,\n"
//            + "            \"error\": \"Feature not enabled for customer f1f34638-8a85-4923-b8bb-d7851d30db9c: requesting company feature did not return status 200: was 404: error during request to metadata service\"\n"
//            + "        }\n"
//            + "    ]\n"
//            + "}").build();
        return Response.accepted().build();
    }



    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response getFeatures() {
        return Response.status(202).entity(localdev_customer_bulk_feats).build();
    }

    public static String localdev_customer_bulk_feats = "{\n"
        + "    \"status\": 200,\n"
        + "    \"errmsg\": \"OK\",\n"
        + "    \"data\": {\n"
        + "        \"total\": 1,\n"
        + "        \"items\": [\n"
        + "            {\n"
        + "                \"uuid\": \"5b8188db-c6b9-44d5-9d08-f8dffa694218\",\n"
        + "                \"userPortalAccessAllowed\": true,\n"
        + "                \"name\": \"localdev\",\n"
        + "                \"server\": \"santaba\",\n"
        + "                \"pod\": \"localdev\",\n"
        + "                \"status\": \"active\",\n"
        + "                \"createdBy\": \"admin\",\n"
        + "                \"createdAt\": \"1632746387000\",\n"
        + "                \"lmsupportEnabled\": true,\n"
        + "                \"lastLoginEmail\": \"siddharth.kulkarni@logicmonitor.com\",\n"
        + "                \"lastLoginUserName\": \"siddharth.kulkarni@logicmonitor.com\",\n"
        + "                \"lastLoginDate\": 1669619494000,\n"
        + "                \"numDevices\": 1009,\n"
        + "                \"customerFeaturesList\": [\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"lm logs advanced search\",\n"
        + "                        \"featureIdentifier\": \"lm logs advanced search\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"lm logs\",\n"
        + "                        \"featureIdentifier\": \"log anomalies\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"lm saas in beta\",\n"
        + "                        \"featureIdentifier\": \"lm saas in beta\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"7\",\n"
        + "                        \"mainFeatureName\": \"chat support\",\n"
        + "                        \"featureIdentifier\": \"chat support\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"netflow\",\n"
        + "                        \"featureIdentifier\": \"netflow\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"Analysis Maps\",\n"
        + "                        \"featureIdentifier\": \"Analysis Maps\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"extra devices\",\n"
        + "                        \"featureIdentifier\": \"extra devices\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"google cloud\",\n"
        + "                        \"featureIdentifier\": \"google cloud\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"ai alert suppression\",\n"
        + "                        \"featureIdentifier\": \"ai alert suppression\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"legacy cloud add and manage\",\n"
        + "                        \"featureIdentifier\": \"legacy cloud add and manage\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"cloud onboarding\",\n"
        + "                        \"featureIdentifier\": \"cloud onboarding\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"topology\",\n"
        + "                        \"featureIdentifier\": \"topology\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"dynamic threshold upper lower bound\",\n"
        + "                        \"featureIdentifier\": \"dynamic threshold upper lower bound\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"topology interface mapping\",\n"
        + "                        \"featureIdentifier\": \"topology interface mapping\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"test sandbox\",\n"
        + "                        \"featureIdentifier\": \"test sandbox\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"paas cloud\",\n"
        + "                        \"featureIdentifier\": \"paas cloud\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"autobalancedcollectors\",\n"
        + "                        \"featureIdentifier\": \"autobalancedcollectors\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"webex monitoring\",\n"
        + "                        \"featureIdentifier\": \"webex monitoring\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"alert dependency\",\n"
        + "                        \"featureIdentifier\": \"alert dependency\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"760\",\n"
        + "                        \"mainFeatureName\": \"lmes data storage period\",\n"
        + "                        \"featureIdentifier\": \"lmes data storage period\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"network whitelisting\",\n"
        + "                        \"featureIdentifier\": \"network whitelisting\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"logicmodule exchange\",\n"
        + "                        \"featureIdentifier\": \"logicmodule exchange\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"lm container monitoring\",\n"
        + "                        \"featureIdentifier\": \"k8s argus\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"anomaly detection\",\n"
        + "                        \"featureIdentifier\": \"anomaly detection\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"lm logs enterprise\",\n"
        + "                        \"featureIdentifier\": \"lm logs enterprise\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"saas office365 audit logs\",\n"
        + "                        \"featureIdentifier\": \"saas office365 audit logs\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"light devices\",\n"
        + "                        \"featureIdentifier\": \"light devices\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"dynamic thresholds v2\",\n"
        + "                        \"featureIdentifier\": \"dynamic thresholds v2\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"lm logs unlimited\",\n"
        + "                        \"featureIdentifier\": \"lm logs unlimited\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"760\",\n"
        + "                        \"mainFeatureName\": \"tsdb data view period\",\n"
        + "                        \"featureIdentifier\": \"tsdb data view period\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"saml\",\n"
        + "                        \"featureIdentifier\": \"saml\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"integration audit logs\",\n"
        + "                        \"featureIdentifier\": \"integration audit logs\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"lm logs ga\",\n"
        + "                        \"featureIdentifier\": \"lm logs ga\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"Analysis Graphs\",\n"
        + "                        \"featureIdentifier\": \"Analysis Graphs\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"azure monitoring\",\n"
        + "                        \"featureIdentifier\": \"azure monitoring\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"760\",\n"
        + "                        \"mainFeatureName\": \"tsdb data storage period\",\n"
        + "                        \"featureIdentifier\": \"tsdb data storage period\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"lm service insight\",\n"
        + "                        \"featureIdentifier\": \"business service\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"{ \\\"adminusercount\\\": 1, \\\"readonlyusercount\\\": 1 }\",\n"
        + "                        \"mainFeatureName\": \"rbac\",\n"
        + "                        \"featureIdentifier\": \"rbac\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"wildvalue as uuid\",\n"
        + "                        \"featureIdentifier\": \"wildvalue as uuid\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"lm saas monitoring\",\n"
        + "                        \"featureIdentifier\": \"saas monitoring\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"log source\",\n"
        + "                        \"featureIdentifier\": \"log source\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"aws monitoring\",\n"
        + "                        \"featureIdentifier\": \"aws monitoring\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"uiv4point2 exchange\",\n"
        + "                        \"featureIdentifier\": \"uiv4point2 exchange\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"385\",\n"
        + "                        \"mainFeatureName\": \"lmes data view period\",\n"
        + "                        \"featureIdentifier\": \"lmes data view period\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"5|SUP1\",\n"
        + "                        \"mainFeatureName\": \"zendesk chat support\",\n"
        + "                        \"featureIdentifier\": \"zendesk chat support\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"cloud monitoring\",\n"
        + "                        \"featureIdentifier\": \"cloud monitoring\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"plg notification\",\n"
        + "                        \"featureIdentifier\": \"plg notification\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"websites\",\n"
        + "                        \"featureIdentifier\": \"websites\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"uiv4 resources\",\n"
        + "                        \"featureIdentifier\": \"uiv4 resources\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"uiv4 services\",\n"
        + "                        \"featureIdentifier\": \"uiv4 services\"\n"
        + "                    },\n"
        + "                    {\n"
        + "                        \"id\": 0,\n"
        + "                        \"uuid\": null,\n"
        + "                        \"subFeatureId\": 0,\n"
        + "                        \"limiterId\": 0,\n"
        + "                        \"lastUpdatedBy\": null,\n"
        + "                        \"lastUpdatedEpoch\": 0,\n"
        + "                        \"createdEpoch\": 0,\n"
        + "                        \"subFeatureName\": null,\n"
        + "                        \"limiterName\": \"true\",\n"
        + "                        \"mainFeatureName\": \"child account\",\n"
        + "                        \"featureIdentifier\": \"child account\"\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"lastUpdatedBy\": null,\n"
        + "                \"billingAccount\": null,\n"
        + "                \"currentSKU\": \"\"\n"
        + "            }\n"
        + "        ]\n"
        + "    }\n"
        + "}\n"
        + "\n";
}
